### ISSUE TITLE
I don't like this

### ISSUE THREAD

**Issue by liam-jones-lucout** [cassiozen/TDungeon#10] opened 2022-09-24 14:29 UTC
It makes me feel things. Weird things.

**Comment by cassiozen** [comment] 2022-09-24 18:17
Duplicate of Typescript/thisMakesMeFeelWeirdFeelingsInside

Closing. Feel free to reopen if you feelings progress to a different stage of grief.

**Closed as not planned** 2022-09-24 18:17 UTC
